### ISSUE TITLE
SEVERE: The specified user database [conf/tomcat-users.xml] could not be found

### ISSUE THREAD

**Issue by HWSKY** [adashen/vscode-tomcat#131]
At select apache folder to run my web service, The launch failed at initialize 

> Apache tomcat server is running normally

> The machine has all dependencies to running the plugin

``usage: java org.apache.catalina.startup.Catalina [ -config {pathname} ] [ -nonaming ]  { -help | start | stop }
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/9.0.5
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Feb 6 2018 21:42:23 UTC
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         9.0.5.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 10
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            10.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Program Files\Java\jre1.8.0_161
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_161-b12
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         C:\Users\kakai\AppData\Roaming\Code\User\workspaceStorage\e45f73f0c867d08cc25ff70f56efaf90\adashen.vscode-tomcat\tomcat\Tomcat 9.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         C:\Program Files\Apache Software Foundation\Tomcat 9.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=C:\Users\kakai\AppData\Roaming\Code\User\workspaceStorage\e45f73f0c867d08cc25ff70f56efaf90\adashen.vscode-tomcat\tomcat\Tomcat 9.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=c:\Program Files\Apache Software Foundation\Tomcat 9.0
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=C:\Users\kakai\AppData\Roaming\Code\User\workspaceStorage\e45f73f0c867d08cc25ff70f56efaf90\adashen.vscode-tomcat\tomcat\Tomcat 9.0\temp
Feb 24, 2018 11:31:51 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF8
Feb 24, 2018 11:31:51 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\ImageMagick-7.0.3-Q16;C:\Users\kakai\.dnx\bin;C:\WINDOWS;C:\mingw64\bin;C:\CMake\bin;C:\ctags58;C:\LLVM\bin;C:\GNUGlobal\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\kakai\AppData\Local\Programs\Python\Python36;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Program Files\LLVM\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\oc;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Ruby23-x64\bin;C:\Users\kakai\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\kakai\AppData\Local\Programs\Python\Python36\;C:\Users\kakai\AppData\Local\Microsoft\WindowsApps;C:\Users\kakai\AppData\Roaming\npm;C:\Program Files\Heroku\bin;C:\Users\kakai\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin;;.]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Feb 24, 2018 11:31:52 AM org.apache.catalina.util.LifecycleBase handleSubClassException
SEVERE: Failed to initialize component [Connector[HTTP/1.1-8080]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:935)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:530)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:852)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:633)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:353)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:493)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:227)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:202)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1043)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:540)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:932)
	... 13 more

Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-nio-8009"]
Feb 24, 2018 11:31:52 AM org.apache.catalina.util.LifecycleBase handleSubClassException
SEVERE: Failed to initialize component [Connector[AJP/1.3-8009]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:935)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:530)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:852)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:633)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:353)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:493)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:227)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:202)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1043)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:540)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:932)
	... 13 more

Feb 24, 2018 11:31:52 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1046 ms
Feb 24, 2018 11:31:52 AM org.apache.catalina.users.MemoryUserDatabase open
SEVERE: The specified user database [conf/tomcat-users.xml] could not be found
Feb 24, 2018 11:31:52 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Feb 24, 2018 11:31:52 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/9.0.5
Feb 24, 2018 11:31:52 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [C:\Users\kakai\AppData\Roaming\Code\User\workspaceStorage\e45f73f0c867d08cc25ff70f56efaf90\adashen.vscode-tomcat\tomcat\Tomcat 9.0\webapps\ROOT]
Feb 24, 2018 11:31:52 AM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [109] milliseconds.
Feb 24, 2018 11:31:52 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [C:\Users\kakai\AppData\Roaming\Code\User\workspaceStorage\e45f73f0c867d08cc25ff70f56efaf90\adashen.vscode-tomcat\tomcat\Tomcat 9.0\webapps\ROOT] has finished in [636] ms
Feb 24, 2018 11:31:52 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 694 ms
Feb 24, 2018 11:31:52 AM org.apache.catalina.core.StandardServer await
SEVERE: StandardServer.await: create[localhost:8005]: 
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:422)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:770)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:716)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:353)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:493)

Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-nio-8009"]
Feb 24, 2018 11:31:52 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Catalina]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8080"]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-nio-8009"]
Feb 24, 2018 11:31:52 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-nio-8009"]
``

**Comment by HWSKY** [comment]
It just needs stop any services and dependences linked to my current apache server to running it. It seems i will need an exclusive apache tomcat to vscode.
