### ISSUE TITLE
Run on Tomcat server again

### ISSUE THREAD

**Issue by Steve30** [adashen/vscode-tomcat#225]
- VSCode Version: 1.27
- OS Version: Linux
- Tomcat Extension Version: 8.5.33

Steps to Reproduce:

1.  Select 'Run on Tomcat server', the server is started (green)
2.  Re-select 'Run on Tomcat server', the server is started and stopped lately (red), because the server is running.

Suggest: Please stop the server, if it is running.

**Comment by SummerSun** [comment]
`Re-select 'Run on Tomcat server', the server is started and stopped lately (red), because the server is running.`
Could you explain a little more about this?
 `Re-Select 'Run on Tomcat Server'`, if the server is running, the war file should be just run on it.

**Comment by Steve30** [comment]
Because the war file change

**Comment by Steve30** [comment]
` ERR Cannot read property 'getValue' of undefined: TypeError: Cannot read property 'getValue' of undefined
    at t.e.getContextKeyValue (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1501:304)
    at e.get (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:1500:236)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2426:941
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at Object.dispose (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3302:1008)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:64:281
    at Array.forEach (<anonymous>)
    at Object.i [as dispose] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:64:249)
    at e.dispose (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3198:996)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3198:146
    at Map.forEach (<anonymous>)
    at e.dispose (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3198:117)
    at t.dispose (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3243:893)
    at w._stopExtensionHostProcess (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3248:156)
    at w._onExtensionHostCrashed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3248:901)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3248:680
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at t._onExtHostProcessExit (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3152:164)
    at ChildProcess.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3147:535)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

**Comment by SummerSun** [comment]
If you want to deploy the changed war file to the server, you'd need to stop the server first and do the deploy again.

`And sometimes the extension is broken.` Does the broken related to the re-deploy? If yes, could you please describe the repro steps here?

**Comment by Steve30** [comment]
No re-deploy, just in sometimes.

**Comment by Steve30** [comment]
One plugin cause the problem
