### ISSUE TITLE
error running war on server

### ISSUE THREAD

**Issue by SalvatoreCognetta** [adashen/vscode-tomcat#261]
- VSCode Version:1.36.1
- OS Version: win10.0.16299
- Tomcat Extension Version: 0.11.1

Steps to Reproduce:

1.Run war file on tomcat server

Hello, the new version give me this problem when i try to run war file on tomcat server:

ERR spawn jar ENOENT: Error: spawn jar ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at Process.asyncWrap [as onexit] (C:\Users\user\\.vscode\extensions\adashen.vscode-tomcat-0.11.1\node_modules\async-listener\glue.js:188:31)
	at onErrorNT (internal/child_process.js:407:16)
	at asyncWrap (C:\Users\user\\.vscode\extensions\adashen.vscode-tomcat-0.11.1\node_modules\async-listener\glue.js:188:31)
	at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by SalvatoreCognetta** [comment]
Solved! As mentioned in [https://github.com/adashen/vscode-tomcat/issues/33](url), i have to set the java enviroment variable in windows (i missed to update java path).
So to solve this problem i followed this guide: [https://javatutorial.net/set-java-home-windows-10](url)
